// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RequestDeadlineFormController from "./request_deadline_form_controller.js"
application.register("request-deadline-form", RequestDeadlineFormController)

import UserInfoController from "./user_info_controller.js"
application.register("user-info", UserInfoController)

import UserListItemController from "./user_list_item_controller.js"
application.register("user-list-item", UserListItemController)
