// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__WeekdayTemplateListItemController from "./admin/weekday_template_list_item_controller.js"
application.register("admin--request-deadline-list-item", Admin__WeekdayTemplateListItemController)

import Admin__UserInfoController from "./admin/user_info_controller.js"
application.register("admin--user-info", Admin__UserInfoController)

import Admin__UserListItemController from "./admin/user_list_item_controller.js"
application.register("admin--user-list-item", Admin__UserListItemController)

import Helpers__DropdownController from "./helpers/dropdown_controller.js"
application.register("helpers--dropdown", Helpers__DropdownController)
