shared:
  calendar_date:
    statuses:
      date_in_future:
        css:
          border: 'border-gray-300'
          background: 'bg-gray-300'
          text-primary: 'text-gray-300'
          text-secondary: 'text-gray-900'
        icon: 'clock'
      awaiting_light_requests:
        css:
          border: 'border-sky-300'
          background: 'bg-sky-300'
          text-primary: 'text-sky-300'
          text-secondary: 'text-gray-900'
        icon: 'collection'
      requesting_light:
        css:
          border: 'border-gray-500'
          background: 'bg-gray-500'
          text-primary: 'text-gray-500'
          text-secondary: 'text-gray-900'
        icon: 'status-online'
      light_requested:
        css:
          border: 'border-indigo-300'
          background: 'bg-indigo-300'
          text-primary: 'text-indigo-300'
          text-secondary: 'text-indigo-900'
        icon: 'phone-outgoing'
      not_active_today:
        css:
          border: 'border-purple-700'
          background: 'bg-purple-700'
          text-primary: 'text-purple-400'
          text-secondary: 'text-purple-300'
        icon: 'moon'
      not_requested_until_deadline:
        css:
          border: 'border-purple-700'
          background: 'bg-purple-700'
          text-primary: 'text-purple-400'
          text-secondary: 'text-purple-300'
        icon: 'moon'
      light_dismissed:
        css:
          border: 'border-purple-700'
          background: 'bg-purple-700'
          text-primary: 'text-purple-400'
          text-secondary: 'text-purple-300'
        icon: 'moon'
      light_confirmed:
        css:
          border: 'border-green-400'
          background: 'bg-green-400'
          text-primary: 'text-green-400'
          text-secondary: 'text-gray-900'
        icon: 'light-bulb'
